// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class AnalyzeOneBook
{
    public int ID { get; set; }

    public int BookID { get; set; }

    public long DateRange { get; set; }

    public int Quantity { get; set; }

    public decimal SalesAmount { get; set; }

    public virtual Product Book { get; set; }
}