// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class AnalyzeUserInteraction
{
    public int ID { get; set; }

    public int MemberID { get; set; }

    public int BookID { get; set; }

    public DateTime InteractionDate { get; set; }

    public string InteractionType { get; set; }

    public virtual Product Book { get; set; }

    public virtual Member Member { get; set; }
}