// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class Book
{
    public int Id { get; set; }

    public int CategoryID { get; set; }

    public string Author { get; set; }

    public string Language { get; set; }

    public string Name { get; set; }

    public virtual ICollection<BookPreview> BookPreviews { get; set; } = new List<BookPreview>();

    public virtual ICollection<BookProduct> BookProducts { get; set; } = new List<BookProduct>();

    public virtual Category Category { get; set; }
}