// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class BookPreview
{
    public int PreviewId { get; set; }

    public int BookId { get; set; }

    public string PreviewURL { get; set; }

    public int? PreviewLength { get; set; }

    public string PreviewContent { get; set; }

    public string PreviewType { get; set; }

    public bool? Available { get; set; }

    public virtual Book Book { get; set; }
}