// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class Bookseller
{
    public int ID { get; set; }

    public string Name { get; set; }

    public string ContactPerson { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public int? Compiled { get; set; }

    public string BankAccount { get; set; }

    public virtual ICollection<BookProduct> BookProducts { get; set; } = new List<BookProduct>();

    public virtual ICollection<PdInStock> PdInStocks { get; set; } = new List<PdInStock>();
}