// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class Category
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int DisplayOrder { get; set; }

    public int? DiscountDegree { get; set; }

    public virtual ICollection<Book> Books { get; set; } = new List<Book>();

    public virtual ICollection<UsedBook> UsedBooks { get; set; } = new List<UsedBook>();
}