// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class Comment
{
    public int Id { get; set; }

    public int PostId { get; set; }

    public int? UserId { get; set; }

    public int? EmployeeId { get; set; }

    public string Content { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Post Post { get; set; }

    public virtual Member User { get; set; }
}