// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class CouponType
{
    public int Id { get; set; }

    public string Type { get; set; }

    public virtual ICollection<Coupon> Coupons { get; set; } = new List<Coupon>();
}