// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class CouponRedemption
{
    public int UsageID { get; set; }

    public int CouponID { get; set; }

    public int MemberId { get; set; }

    public DateTime RedemptionDate { get; set; }

    public virtual Coupon Coupon { get; set; }
}