// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class EBooksPermission
{
    public int Id { get; set; }

    public int BookID { get; set; }

    public int MemberID { get; set; }

    public DateTime CreateDate { get; set; }

    public string PermissionType { get; set; }

    public virtual EBook Book { get; set; }

    public virtual Member Member { get; set; }
}