// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class Employee
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool Gender { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Position { get; set; }

    public int GroupId { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public bool EmailVerified { get; set; }

    public string VerificationCode { get; set; }

    public DateTime? VerificationCodeExpiration { get; set; }

    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual GroupPermission Group { get; set; }

    public virtual ICollection<News> News { get; set; } = new List<News>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}