// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class Favorite
{
    public int FavoriteID { get; set; }

    public int? MemberID { get; set; }

    public int? ItemID { get; set; }

    public virtual Member Member { get; set; }
}