// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class Keyword
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<ProductKeyword> ProductKeywords { get; set; } = new List<ProductKeyword>();
}