// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class LogisticsOrder
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public string TrackingNumber { get; set; }

    public DateTime EstimatedDeliveryDate { get; set; }

    public DateTime ActualDeliveryDate { get; set; }

    public string RecipientName { get; set; }

    public string RecipientPhone { get; set; }

    public string RecipientAddress { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<Return> Returns { get; set; } = new List<Return>();
}