// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class Member
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool Gender { get; set; }

    public DateTime DateOfBirth { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string MembersLevel { get; set; }

    public string Address { get; set; }

    public string PhoneNumber { get; set; }

    public int Points { get; set; }

    public bool EmailVerified { get; set; }

    public string VerificationCode { get; set; }

    public int? VerificationCodeExpiration { get; set; }

    public DateTime CreatedAt { get; set; }

    public string ResetToken { get; set; }

    public DateTime? ResetTokenExpiration { get; set; }

    public virtual ICollection<AnalyzeUserInteraction> AnalyzeUserInteractions { get; set; } = new List<AnalyzeUserInteraction>();

    public virtual ICollection<BookReview> BookReviews { get; set; } = new List<BookReview>();

    public virtual Cart Cart { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<EBooksPermission> EBooksPermissions { get; set; } = new List<EBooksPermission>();

    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<PointsHistory> PointsHistories { get; set; } = new List<PointsHistory>();

    public virtual ICollection<Return> Returns { get; set; } = new List<Return>();

    public virtual ICollection<UsedBook> UsedBooks { get; set; } = new List<UsedBook>();

    public virtual ICollection<UsedBooksAllocationRecord> UsedBooksAllocationRecords { get; set; } = new List<UsedBooksAllocationRecord>();

    public virtual ICollection<UsedBooksCart> UsedBooksCarts { get; set; } = new List<UsedBooksCart>();

    public virtual ICollection<UsedBooksOrder> UsedBooksOrderBuyers { get; set; } = new List<UsedBooksOrder>();

    public virtual ICollection<UsedBooksOrder> UsedBooksOrderSellers { get; set; } = new List<UsedBooksOrder>();

    public virtual ICollection<WriteBookReview> WriteBookReviews { get; set; } = new List<WriteBookReview>();
}