// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class Order
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime OrderDate { get; set; }

    public int TotalAmount { get; set; }

    public string Status { get; set; }

    public int? DiscountAmount { get; set; }

    public string Message { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string MerchantTradeNo { get; set; }

    public virtual ICollection<LogisticsOrder> LogisticsOrders { get; set; } = new List<LogisticsOrder>();

    public virtual Member Member { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<Refund> Refunds { get; set; } = new List<Refund>();

    public virtual ICollection<Return> Returns { get; set; } = new List<Return>();
}