// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class PdInStock
{
    public int ID { get; set; }

    public int ProductId { get; set; }

    public int? SupplierID { get; set; }

    public int Qty { get; set; }

    public DateTime BuyDate { get; set; }

    public decimal BuyPrice { get; set; }

    public virtual Product Product { get; set; }

    public virtual Bookseller Supplier { get; set; }
}