// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class PointsHistory
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int PointChange { get; set; }

    public string ChangeReason { get; set; }

    public DateTime ChangeDate { get; set; }

    public virtual Member Member { get; set; }
}