// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class Post
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public int AuthorId { get; set; }

    public DateTime PublishDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string Slug { get; set; }

    public bool IsPublished { get; set; }

    public virtual Employee Author { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<Category1> Categories { get; set; } = new List<Category1>();

    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
}