// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public string ProductStatus { get; set; }

    public string Description { get; set; }

    public string Category { get; set; }

    public int Stock { get; set; }

    public int? DetailsCategoryId { get; set; }

    public decimal? Offer { get; set; }

    public int? DiscountDegree { get; set; }

    public decimal? RealPrice { get; set; }

    public virtual ICollection<AnalyzeOneBook> AnalyzeOneBooks { get; set; } = new List<AnalyzeOneBook>();

    public virtual ICollection<AnalyzeSale> AnalyzeSales { get; set; } = new List<AnalyzeSale>();

    public virtual ICollection<AnalyzeUserInteraction> AnalyzeUserInteractions { get; set; } = new List<AnalyzeUserInteraction>();

    public virtual ICollection<BookProduct> BookProducts { get; set; } = new List<BookProduct>();

    public virtual ICollection<CartDetail> CartDetails { get; set; } = new List<CartDetail>();

    public virtual ProductDetailsCategory DetailsCategory { get; set; }

    public virtual ICollection<EBook> EBooks { get; set; } = new List<EBook>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<PdInStock> PdInStocks { get; set; } = new List<PdInStock>();

    public virtual ICollection<ProductKeyword> ProductKeywords { get; set; } = new List<ProductKeyword>();

    public virtual ICollection<ProductPicture> ProductPictures { get; set; } = new List<ProductPicture>();

    public virtual ICollection<QtyBookInventory> QtyBookInventories { get; set; } = new List<QtyBookInventory>();

    public virtual ICollection<QtyflawBook> QtyflawBooks { get; set; } = new List<QtyflawBook>();

    public virtual ICollection<WriteBookReview> WriteBookReviews { get; set; } = new List<WriteBookReview>();
}