// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class ProductKeyword
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public int KeywordId { get; set; }

    public virtual Keyword Keyword { get; set; }

    public virtual Product Product { get; set; }
}