// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class PromotionEvent
{
    public int EventID { get; set; }

    public string EventName { get; set; }

    public string EventSerialNumber { get; set; }

    public string EventDescription { get; set; }

    public string DiscountType { get; set; }

    public string EventType { get; set; }

    public decimal? DiscountRate { get; set; }

    public string OfferStatus { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public string EventDetails { get; set; }

    public byte[] EventFile { get; set; }
}