// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class Promotion
{
    public int PromotionID { get; set; }

    public string PromotionName { get; set; }

    public string Type { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }
}