// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class QtyBookInventory
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public decimal BuyPrice { get; set; }

    public int TotalQty { get; set; }

    public string State { get; set; }

    public string Remark { get; set; }

    public virtual Product Product { get; set; }
}