// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class Refund
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public DateTime ApplicationDate { get; set; }

    public int Amount { get; set; }

    public string RefundStatus { get; set; }

    public virtual Order Order { get; set; }
}