// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class Return
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int MemberId { get; set; }

    public int LogisticsOrderId { get; set; }

    public int Quantity { get; set; }

    public string ReturnReason { get; set; }

    public string Status { get; set; }

    public DateTime ReturnDate { get; set; }

    public DateTime ProcessdDate { get; set; }

    public virtual LogisticsOrder LogisticsOrder { get; set; }

    public virtual Member Member { get; set; }

    public virtual Order Order { get; set; }
}