// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class UsedBookPaymentRecord
{
    public int Id { get; set; }

    public int PaymentAmount { get; set; }

    public string PaymentNumber { get; set; }

    public string OrderId { get; set; }

    public bool status { get; set; }
}