// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class UsedBookBuyerInformation
{
    public int Id { get; set; }

    public string OrderId { get; set; }

    public string RecipientName { get; set; }

    public string RecipientPhone { get; set; }

    public string RecipientAddress { get; set; }

    public string RecipientEmail { get; set; }

    public string Remark { get; set; }
}