// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class UsedBooksCart
{
    public int Id { get; set; }

    public int MemberID { get; set; }

    public int BookID { get; set; }

    public DateTime AddToCartDate { get; set; }

    public virtual UsedBook Book { get; set; }

    public virtual Member Member { get; set; }
}