// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class UsedBooksOrderDetail
{
    public int Id { get; set; }

    public int OrderID { get; set; }

    public int BookID { get; set; }

    public int UnitPrice { get; set; }

    public virtual UsedBook Book { get; set; }

    public virtual UsedBooksOrder Order { get; set; }
}