// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class UsedBooksAllocationRecord
{
    public int Id { get; set; }

    public int OrderID { get; set; }

    public int MemberID { get; set; }

    public string AllocationAccount { get; set; }

    public int AllocationAmount { get; set; }

    public int PlatformShareAmount { get; set; }

    public virtual Member Member { get; set; }

    public virtual UsedBooksOrder Order { get; set; }
}