// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class UsedBooksReturn
{
    public int Id { get; set; }

    public int OrderID { get; set; }

    public int MemberID { get; set; }

    public DateTime ApplicationDate { get; set; }

    public string ReturnReason { get; set; }

    public string Status { get; set; }

    public DateTime? ProcessedDate { get; set; }

    public virtual UsedBooksOrder Order { get; set; }
}