// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class UsedBook
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int? CategoryId { get; set; }

    public bool ProductStatus { get; set; }

    public string Name { get; set; }

    public string Authors { get; set; }

    public string Description { get; set; }

    public string PublisherName { get; set; }

    public DateTime? PublishDate { get; set; }

    public string ISBN { get; set; }

    public decimal Price { get; set; }

    public byte[] Picture { get; set; }

    public DateTime ReleaseDate { get; set; }

    public string BookStatus { get; set; }

    public bool IsDeleted { get; set; }

    public string WebReaderLink { get; set; }

    public string SmallThumbnailPicture { get; set; }

    public string ThumbnailPicture { get; set; }

    public string SmallPicture { get; set; }

    public virtual Category Category { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<UsedBooksCart> UsedBooksCarts { get; set; } = new List<UsedBooksCart>();

    public virtual ICollection<UsedBooksOrderDetail> UsedBooksOrderDetails { get; set; } = new List<UsedBooksOrderDetail>();
}