// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class UsedBookOrderMessage
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int MemberId { get; set; }

    public string Message { get; set; }

    public DateTime? DateTime { get; set; }
}