// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendForFrontend.Models.EFModels;

public partial class UsedBooksOrder
{
    public int Id { get; set; }

    public int BuyerId { get; set; }

    public int SellerId { get; set; }

    public DateTime OrderDate { get; set; }

    public int TotalAmount { get; set; }

    public string Status { get; set; }

    public int ShippingFee { get; set; }

    public string PaymentMethod { get; set; }

    public virtual Member Buyer { get; set; }

    public virtual Member Seller { get; set; }

    public virtual ICollection<UsedBooksAllocationRecord> UsedBooksAllocationRecords { get; set; } = new List<UsedBooksAllocationRecord>();

    public virtual ICollection<UsedBooksLogisticsOrder> UsedBooksLogisticsOrders { get; set; } = new List<UsedBooksLogisticsOrder>();

    public virtual ICollection<UsedBooksOrderDetail> UsedBooksOrderDetails { get; set; } = new List<UsedBooksOrderDetail>();

    public virtual ICollection<UsedBooksReturn> UsedBooksReturns { get; set; } = new List<UsedBooksReturn>();
}