// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MinimalAPIs.MinimalAPIs.Models;

[Table("CouponRedemption")]
public partial class CouponRedemption
{
    [Key]
    public int UsageID { get; set; }

    public int CouponID { get; set; }

    public int MemberId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RedemptionDate { get; set; }

    [ForeignKey("CouponID")]
    [InverseProperty("CouponRedemptions")]
    public virtual Coupon Coupon { get; set; }
}