// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MinimalAPIs.MinimalAPIs.Models;

public partial class Coupon
{
    [Key]
    public int CouponID { get; set; }

    public int PromotionID { get; set; }

    [Required]
    [StringLength(16)]
    public string Code { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndDate { get; set; }

    [Required]
    public bool? Valid { get; set; }

    [Required]
    [StringLength(200)]
    public string Description { get; set; }

    public int AvailabilityCount { get; set; }

    [Required]
    [StringLength(15)]
    public string UsingStatus { get; set; }

    public int MinimumValue { get; set; }

    public int DiscountValue { get; set; }

    public int DiscountLimit { get; set; }

    public int CouponTypeId { get; set; }

    [InverseProperty("Coupon")]
    public virtual ICollection<CouponRedemption> CouponRedemptions { get; set; } = new List<CouponRedemption>();

    [ForeignKey("CouponTypeId")]
    [InverseProperty("Coupons")]
    public virtual CouponType CouponType { get; set; }
}