// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MinimalAPIs.MinimalAPIs.Models;

public partial class PromotionEvent
{
    [Key]
    public int EventID { get; set; }

    [Required]
    [StringLength(255)]
    public string EventName { get; set; }

    [Required]
    [StringLength(100)]
    public string EventSerialNumber { get; set; }

    [StringLength(500)]
    public string EventDescription { get; set; }

    [Required]
    [StringLength(100)]
    public string DiscountType { get; set; }

    [Required]
    [StringLength(100)]
    public string EventType { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? DiscountRate { get; set; }

    [Required]
    [StringLength(100)]
    public string OfferStatus { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndDate { get; set; }

    public string EventDetails { get; set; }

    public byte[] EventFile { get; set; }
}