// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MinimalAPIs.MinimalAPIs.Models;

public partial class Promotion
{
    [Key]
    public int PromotionID { get; set; }

    [Required]
    [StringLength(50)]
    public string PromotionName { get; set; }

    [Required]
    [StringLength(20)]
    public string Type { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndDate { get; set; }
}